# Generated by Django 5.1.2 on 2024-12-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsApp', '0003_mentor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='user',
        ),
    ]
